name = "genidoc-backend"
main = "src/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[vars]
JWT_SECRET = "genidoc-secret-key-2024"

[[d1_databases]]
binding = "DB"
database_name = "genidoc-db"
database_id = "e9f6a319-8a6d-4c47-b4f9-45c7385817f8"
